version: "3.8"
services:
  app:
    container_name: app
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - API_HOST=app
      - PORT=80
      - DB_HOST=postgres
      - DATABASE_URL=postgres://allocation:abc123@postgres:5432/allocation
      - DB_PASSWORD=abc123
    ports:
      - "3000:80"
  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: